# https://github.com/GaryLove/inclusive-forms/blob/master/.github/workflows/11ty-build.yml
name: main

on:
  push:
    paths-ignore:
    - '.github/**'
    - '.vscode/**'

jobs:
  build_deploy:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: TartanLlama/actions-eleventy@v1.2
        with:
          install_dependencies: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v1.1.0
        env:
          PUBLISH_DIR: _site
          PUBLISH_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}